# Linear Regression Algorithm using Normal Equation

In [1]:
#Importing the libraries and accomodating the data into a pandas dataframe
import numpy as np
import pandas as pd
df = pd.read_csv('USA_Housing.csv')
df.drop('Address',axis = 1,inplace = True)

### The equations we will be using is: 
### 1.

### \begin{align} 
h_{\theta}(X) & = \theta_{0} + \theta_{1}.x_{1} + \theta_{2}.x_{2} + \theta_{3}.x_{3} + \theta_{4}.x_{4} + \theta_{5}.x_{5}
\end{align}

#### where y hat is the predicted value, $θ_{0}$ is the intercept, $θ_{1}$, $θ_{2}$, $θ_{3}$, $θ_{4}$ and $θ_{5}$ are the coefficients and $X_{1}$, $X_{2}$, $X_{3}$, $X_{4}$ and $X_{5}$ are the independent variables. $X_{0}$ will be a column of 1s in the matrix X. 

### 2.
### \begin{align} 
\theta = (X.X^{T})^{-1}.(X^{T}y)
\end{align}

#### where X is the matrix of features(Independent variables) and y is the vector of target(dependent variable)


#### The first equation we will be using in matrix form to solve it all at once.

In [2]:
#Checking how our data looks
df.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  
0                          4.09     23086.800503  1.059034e+06  
1                          3.09     40173.072174  1.505891e+06  
2                          5.13     36882.159400  1.058988e+06  
3                          3.26     34310.242831  1.260617e+06  
4                          4.23     26354.109472  6.309435e+05

In [3]:
#Checking the shape of our dataset
df.shape

(5000, 6)

#### So our data has 5000 records and 6 features/columns

In [4]:
#Changing the dataframe to an array for train/test split
df_to_array = df.values

In [5]:
#Checking how our array looks
df_to_array

array([[7.95454586e+04, 5.68286132e+00, 7.00918814e+00, 4.09000000e+00,
        2.30868005e+04, 1.05903356e+06],
       [7.92486425e+04, 6.00289981e+00, 6.73082102e+00, 3.09000000e+00,
        4.01730722e+04, 1.50589091e+06],
       [6.12870672e+04, 5.86588984e+00, 8.51272743e+00, 5.13000000e+00,
        3.68821594e+04, 1.05898799e+06],
       ...,
       [6.33906869e+04, 7.25059061e+00, 4.80508098e+00, 2.13000000e+00,
        3.32661455e+04, 1.03072958e+06],
       [6.80013312e+04, 5.53438842e+00, 7.13014386e+00, 5.44000000e+00,
        4.26256202e+04, 1.19865687e+06],
       [6.55105818e+04, 5.99230531e+00, 6.79233610e+00, 4.07000000e+00,
        4.65012838e+04, 1.29895048e+06]])

In [6]:
#Shuffling data to make it random before splitting then splitting into 80% training and 20% testing
np.random.shuffle(df_to_array)
train, test = df_to_array[:3750,:], df_to_array[3750:,:]

In [7]:
train

array([[5.75682171e+04, 6.54484553e+00, 7.21482412e+00, 4.31000000e+00,
        3.43854132e+04, 9.49684410e+05],
       [8.00779305e+04, 5.73952183e+00, 7.43700914e+00, 4.50000000e+00,
        3.07743943e+04, 1.60334267e+06],
       [6.55940674e+04, 7.49280332e+00, 7.11368510e+00, 3.30000000e+00,
        2.45805637e+04, 1.17998732e+06],
       ...,
       [8.11078960e+04, 6.53747789e+00, 8.39101604e+00, 6.30000000e+00,
        4.09369896e+04, 1.78732451e+06],
       [6.23584041e+04, 6.87097676e+00, 7.32697575e+00, 4.19000000e+00,
        3.53659456e+04, 1.21227636e+06],
       [6.92014374e+04, 5.55904731e+00, 5.72736776e+00, 3.42000000e+00,
        4.25735780e+04, 1.10966556e+06]])

In [8]:
test

array([[6.40552842e+04, 7.55289055e+00, 7.33722945e+00, 5.21000000e+00,
        2.78046052e+04, 1.28900822e+06],
       [6.46619303e+04, 4.65669575e+00, 5.66025312e+00, 2.44000000e+00,
        4.94571794e+04, 8.75904529e+05],
       [6.78460487e+04, 5.37970485e+00, 6.10386333e+00, 4.15000000e+00,
        2.74420962e+04, 8.79511196e+05],
       ...,
       [6.07318823e+04, 6.22571936e+00, 8.54583209e+00, 5.46000000e+00,
        3.53410678e+04, 1.23547555e+06],
       [7.02196904e+04, 5.70724724e+00, 7.60949936e+00, 5.01000000e+00,
        2.85538155e+04, 1.12677841e+06],
       [5.91798686e+04, 6.21548829e+00, 6.51924929e+00, 2.45000000e+00,
        3.35495531e+04, 8.92718091e+05]])

In [9]:
#Diving split data into X and y for machine learning where X will be for independent variables and y for dependent
X_train = train[:,:-1]
X_test = test[:,:-1]
y_train = train[:,-1]
y_test = test[:,-1]

In [10]:
#Making a vector with only 1s as records for X0
x_bias = np.ones((3750,1))

In [11]:
#Adding the column X0
X_train = np.append(x_bias,X_train,axis=1)

In [12]:
#looking at our new array
X_train

array([[1.00000000e+00, 5.75682171e+04, 6.54484553e+00, 7.21482412e+00,
        4.31000000e+00, 3.43854132e+04],
       [1.00000000e+00, 8.00779305e+04, 5.73952183e+00, 7.43700914e+00,
        4.50000000e+00, 3.07743943e+04],
       [1.00000000e+00, 6.55940674e+04, 7.49280332e+00, 7.11368510e+00,
        3.30000000e+00, 2.45805637e+04],
       ...,
       [1.00000000e+00, 8.11078960e+04, 6.53747789e+00, 8.39101604e+00,
        6.30000000e+00, 4.09369896e+04],
       [1.00000000e+00, 6.23584041e+04, 6.87097676e+00, 7.32697575e+00,
        4.19000000e+00, 3.53659456e+04],
       [1.00000000e+00, 6.92014374e+04, 5.55904731e+00, 5.72736776e+00,
        3.42000000e+00, 4.25735780e+04]])

In [13]:
#Checking the new shape
X_train.shape

(3750, 6)

#### To solve the second equation, we will calculate the transpose and the inverse

In [14]:
#Solving the transpose and inverse
x_transpose = np.transpose(X_train)
x_transpose_dot_x = x_transpose.dot(X_train)
var1 = np.linalg.inv(x_transpose_dot_x)

### \begin{align} 
var1 = (X.X^{T})^{-1}
\end{align}

In [15]:
#Checking how var1 looks
var1

array([[ 3.84070284e-02, -1.67621120e-07, -1.63901149e-03,
        -1.88075824e-03,  2.56895541e-05, -1.05964840e-07],
       [-1.67621120e-07,  2.41166776e-12, -3.31309979e-10,
         5.84395564e-10, -4.22828564e-10,  4.54951772e-14],
       [-1.63901149e-03, -3.31309979e-10,  2.76552430e-04,
         1.35083816e-06, -2.06108675e-06,  2.77939863e-10],
       [-1.88075824e-03,  5.84395564e-10,  1.35083816e-06,
         3.37278310e-04, -1.28610140e-04, -2.39019122e-10],
       [ 2.56895541e-05, -4.22828564e-10, -2.06108675e-06,
        -1.28610140e-04,  2.23714996e-04,  6.00374648e-10],
       [-1.05964840e-07,  4.54951772e-14,  2.77939863e-10,
        -2.39019122e-10,  6.00374648e-10,  2.78023060e-12]])

In [16]:
#Checking how var2 looks
var2 = x_transpose.dot(y_train)  

In [17]:
var2

array([4.61510504e+09, 3.25743015e+14, 2.81440872e+10, 3.26537092e+10,
       1.86664441e+10, 1.71975676e+14])

### \begin{align}
var2 = (X^{T}.y)
\end{align}

In [18]:
#Solving the full equation and getting our intercept and  coefficients
theta = var1.dot(var2)
theta

array([-2.63499588e+06,  2.16844736e+01,  1.64619195e+05,  1.20072430e+05,
        2.43431816e+03,  1.51372683e+01])

### \begin{align} 
\theta = (X.X^{T})^{-1}.(X^{T}y)
\end{align}

In [19]:
#Checking the shape of the theta vector
theta.shape

(6,)

#### This is how our theta vector looks:

### \begin{align}
\theta = \left( \begin{array}{c} \theta_0 \\ \theta_1 \\ \theta_2 \\ \theta_3 \\ \theta_4 \\ \theta_5\end{array} \right)
\end{align}

In [20]:
#Appending a column of 1s to our matrix X for testing data 
x_bias = np.ones((1250,1))
X_test = np.append(x_bias,X_test,axis=1)

In [21]:
#Validating the shape of X test matrix
X_test.shape

(1250, 6)

In [22]:
#Calculating the predicted values using dot product for X matrix and theta vector
predicted_values = np.dot(X_test,theta)

In [23]:
#Taking a look at the predicted values
predicted_values

array([1311927.53135889,  967972.21647819,  880219.14325652, ...,
       1281193.35081377, 1185317.36215023,  968071.86124705])

#### Now since our vector θ is of 6x1 dimension and matrix X is of 1250x6, we will get a vector of dimensions 1250x1(By matrix multiplication property)

In [24]:
#Checking the shape of our predicted values vector
predicted_values.shape

(1250,)

In [25]:
#Now to calculate the mean squared error
Mean_Squared_Error = (sum((predicted_values-y_test)**2)/1250)
print(Mean_Squared_Error)

10290526596.970495


In [26]:
max(y_test**2)

5374448602294.948

### \begin{align}
J(\theta) = \frac{1}{n} \sum \limits _{i=1} ^{n} (\hat{y}_i - y_i)^{2}
\end{align}


#### Where n is the sample size, y hat is the predicted value and y is the test value. J(θ) is actually the cost function and is also called mean squared error. Minimizing the cost function to predict accurately is the principle behind Linear Regression.

In [27]:
#Calculating the mean of the testing target values
mean = y_test.mean()

In [28]:
#Finding out the R-squared value to check how are data has fitted to the regression line
R2_score = 1 - sum((predicted_values-y_test)**2)/sum((y_test-mean)**2)
print(R2_score)

0.9193566292948949


### \begin{align}
R^{2} = 1- \frac{\sum \limits _{i=1} ^{n} (\hat{y}_i - y_i)^{2}}{\sum \limits _{i=1} ^{n} ({y}_i - \bar{y}_i)^{2}}
\end{align}

#### Where n is the sample size, y hat is the predicted value and y is the test value

#### R-squared is a statistical measure of how close the data are to the fitted regression line. It is also known as the coefficient of multiple determination for multiple regression. 100% indicates that the model explains all the variability of the response data around its mean.

#### So we have achieved a really high score which is impressive considering the range of $R^{2}$ lies between 0 and 1.